name: Bump tag on file update
on:
  push:
    branches: [master]
    paths: 
      - './*.sha256sum'
  workflow_dispatch: ~

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: "YYYYMMDD"
      - name: Bump tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          CUSTOM_TAG: ${{ steps.current-time.outputs.formattedTime }}
          DEFAULT_BRANCH: master

