name: Periodic updates

on:
  push:
    branches: [ master ]
    paths: [ ./files.list ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: ~

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: "YYYY-MM-DD HH:mm"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update
        run: |
          bash update-files.sh

      - name: Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: .
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: updated ${{ steps.current-time.outputs.formattedTime }} UTC
